version: '3.8'
services:
  postgresDB:
    image: postgres:latest
    environment:
      POSTGRES_USER: worraphong
      POSTGRES_PASSWORD: worraphong2000
      POSTGRES_DB: myDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: worraphong@admin.com
      PGADMIN_DEFAULT_PASSWORD: worraphong2000
    ports:
      - '5050:80'
    depends_on:
      - postgresDB

volumes:
  postgres-data:


